version: '3.8'

networks:
  inception:
    name: inception
    driver:
      bridge

volumes:
  wordpress_db:
    driver:
      local
    driver_opts:
      type:
        none
      o:
        bind
      device:
        ${HOME}/data/wordpress_db
  
  wordpress_files:
    driver:
      local
    driver_opts:
      type:
        none
      o:
        bind
      device:
        ${HOME}/data/wordpress_files



services:

  check_env:
    image: debian:11
    env_file:
      - .env
    environment:
      - DB_DATABASE
      - DB_HOSTNAME
      - DB_USER
      - WP_ADMIN_USR
      - WP_ADMIN_EMAIL
      - WP_USER_NAME
      - WP_USER_EMAIL
    networks:
      - inception
    entrypoint: ["echo", "Environment variables are set."] 

  mariadb:
    container_name: 
      mariadb
    depends_on:
      - check_env
    env_file:
      - .env
    volumes:
      - wordpress_db:/var/lib/mysql
    build:
      context:
        ./requirements/mariadb
      dockerfile: 
        Dockerfile
    networks:
      - inception
    restart:
      always


  wordpress:
    depends_on:
      - mariadb
    container_name:
      wordpress
    env_file:
      - .env
    volumes:
      - wordpress_files:/var/www/html
    build:
      context:
        ./requirements/wordpress
      dockerfile:
        Dockerfile
    networks:
      - inception
    restart:
      always

  nginx:
    depends_on:
      - wordpress
    container_name:
      nginx
    env_file:
      - .env
    volumes:
      - wordpress_files:/var/www/html
      - wordpress_db:/var/lib/mysql
    build:
      context:
        ./requirements/nginx
      dockerfile: 
        Dockerfile
    ports:
      - "443:443"
    networks:
      - inception
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart:
      always