version: '3'

networks:
  inception:
    driver:
      bridge

volumes:
  wordpress_db:
    driver:
      local
    driver_opts:
      type:
        none
      o:
        bind
      device:
        ${HOME}/data/wordpress_db
  
  wordpress_files:
    driver:
      local
    driver_opts:
      type:
        none
      o:
        bind
      device:
        ${HOME}/data/wordpress_files



services:
  mariadb:
    container_name: 
      mariadb
    env_file:
      - .env
    volumes:
      - wordpress_db:/var/lib/mysql
    build:
      context:
        ./requirements/mariadb
      dockerfile: 
        Dockerfile
    networks:
      - inception
    restart:
      always


  wordpress:
    container_name:
      wordpress
    env_file:
      - .env
    volumes:
      - wordpress_files:/var/www/html/wordpress
    build:
      context:
        ./requirements/wordpress
      dockerfile:
        Dockerfile
    networks:
      - inception
    restart:
      always

  nginx:
    container_name:
      nginx
    env_file:
      - .env
    volumes:
      - wordpress_files:/var/www/html/wordpress
    build:
      context:
        ./requirements/nginx
      dockerfile: 
        Dockerfile
    ports:
      - "443:443"
    networks:
      - inception
    restart:
      always
